### ISSUE TITLE
Attivo la seconda opzione del settings - Select Feature of Referencing Layer From Referenced one

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_selectbyrelationshipv3#4]
@slarosa
Riferendomi sempre al progetto allegato: la tabella comuni è sempre una tabella `figlio`, mentre la tabella `province` è sia padre che figlio; infine la tabella `regione` è solo padre:

se selezionassi (con il mouse nella canvas) uno o più comuni, il plugin seleziona tutti i comuni della provincia e la regione interessata, la cosa strana è che nella tabella attributi: 
1. dei comuni: risulta selezionati solo quelli selezionati con il mouse nella canvas;(strano!!!) -vedi (1)
2. delle province: risulta selezionate quelle interessate - OK!
3. delle regioni: risulta selezionate quelle interessate - OK!
aprendo successivamente la tabella attributi dei comuni (vedi screen (2)) la selezione delle righe è corretta.
Forse è un altro bug che non centra nulla con il plugin?

![image](https://user-images.githubusercontent.com/7631137/39966517-5da494b2-56ad-11e8-8cbd-26134e729bc8.png)

**Comment by slarosa** [comment]
@pigreco non riesco a riprodurlo, a me seleziona correttamente, sto usando la QGIS master.

**Comment by pigreco** [comment]
Chiudo issue,
molto probabilmente NON è un problema legato al plugin
