### ISSUE TITLE
il plugin resta attivo anche se l'icona è disattivata

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_selectbyrelationshipv3#5]
@slarosa
prova da fare:
1. plugin attivo, prima icona;
2. selezionare la prima relazione  `rel_prov_com` ;
3. opzioni da attivare: solo la prima lo Zoom;
4. nella TOC selezionare il layer `province_g`;
5. fare una selezione;
6. tutto funziona bene;
7. disattivo plugin, prima icona;
8. seleziono e noto che il plugin è sempre attivo anche se l'icona è disattivata.

**Comment by slarosa** [comment]
bug

**Comment by slarosa** [comment]
Grazie totò, credo di aver sistemato il problema, se mi dai ok dopo i tuoi test pubblichiamo...
[selectby.zip](https://github.com/pigreco/test_selectbyrelationshipv3/files/2006687/selectby.zip)

**Comment by pigreco** [comment]
@slarosa ho appena fatto dei test, il bug è risolto. grazie.

OK, pubblichiamo!!!

chiudo issue
